package ey.samarin.providers.network.models


import com.google.gson.annotations.SerializedName

data class MostActivesModel(
    @SerializedName("body") val body: List<Body>,
    @SerializedName("meta") val meta: Meta,
)

data class Meta(
    @SerializedName("copywrite") val copywrite: String,
    @SerializedName("count") val count: Int,
    @SerializedName("description") val description: String,
    @SerializedName("offset") val offset: Int,
    @SerializedName("processedTime") val processedTime: String,
    @SerializedName("status") val status: Int,
    @SerializedName("total") val total: Int,
    @SerializedName("version") val version: String
)

data class Body(
    @SerializedName("ask") val ask: Double,
    @SerializedName("askSize") val askSize: Int,
    @SerializedName("averageAnalystRating") val averageAnalystRating: String,
    @SerializedName("averageDailyVolume10Day") val averageDailyVolume10Day: Int,
    @SerializedName("averageDailyVolume3Month") val averageDailyVolume3Month: Int,
    @SerializedName("bid") val bid: Double,
    @SerializedName("bidSize") val bidSize: Int,
    @SerializedName("bookValue") val bookValue: Double,
    @SerializedName("cryptoTradeable") val cryptoTradeable: Boolean,
    @SerializedName("currency") val currency: String,
    @SerializedName("customPriceAlertConfidence") val customPriceAlertConfidence: String,
    @SerializedName("displayName") val displayName: String,
    @SerializedName("dividendDate") val dividendDate: Int,
    @SerializedName("dividendRate") val dividendRate: Double,
    @SerializedName("dividendYield") val dividendYield: Double,
    @SerializedName("earningsTimestamp") val earningsTimestamp: Int,
    @SerializedName("earningsTimestampEnd") val earningsTimestampEnd: Int,
    @SerializedName("earningsTimestampStart") val earningsTimestampStart: Int,
    @SerializedName("epsCurrentYear") val epsCurrentYear: Double,
    @SerializedName("epsForward") val epsForward: Double,
    @SerializedName("epsTrailingTwelveMonths") val epsTrailingTwelveMonths: Double,
    @SerializedName("esgPopulated") val esgPopulated: Boolean,
    @SerializedName("exchange") val exchange: String,
    @SerializedName("exchangeDataDelayedBy") val exchangeDataDelayedBy: Int,
    @SerializedName("exchangeTimezoneName") val exchangeTimezoneName: String,
    @SerializedName("exchangeTimezoneShortName") val exchangeTimezoneShortName: String,
    @SerializedName("fiftyDayAverage") val fiftyDayAverage: Double,
    @SerializedName("fiftyDayAverageChange") val fiftyDayAverageChange: Double,
    @SerializedName("fiftyDayAverageChangePercent") val fiftyDayAverageChangePercent: Double,
    @SerializedName("fiftyTwoWeekChangePercent") val fiftyTwoWeekChangePercent: Double,
    @SerializedName("fiftyTwoWeekHigh") val fiftyTwoWeekHigh: Double,
    @SerializedName("fiftyTwoWeekHighChange") val fiftyTwoWeekHighChange: Double,
    @SerializedName("fiftyTwoWeekHighChangePercent") val fiftyTwoWeekHighChangePercent: Double,
    @SerializedName("fiftyTwoWeekLow") val fiftyTwoWeekLow: Double,
    @SerializedName("fiftyTwoWeekLowChange") val fiftyTwoWeekLowChange: Double,
    @SerializedName("fiftyTwoWeekLowChangePercent") val fiftyTwoWeekLowChangePercent: Double,
    @SerializedName("fiftyTwoWeekRange") val fiftyTwoWeekRange: String,
    @SerializedName("financialCurrency") val financialCurrency: String,
    @SerializedName("firstTradeDateMilliseconds") val firstTradeDateMilliseconds: Long,
    @SerializedName("forwardPE") val forwardPE: Double,
    @SerializedName("fullExchangeName") val fullExchangeName: String,
    @SerializedName("gmtOffSetMilliseconds") val gmtOffSetMilliseconds: Int,
    @SerializedName("ipoExpectedDate") val ipoExpectedDate: String,
    @SerializedName("language") val language: String,
    @SerializedName("lastClosePriceToNNWCPerShare") val lastClosePriceToNNWCPerShare: Double,
    @SerializedName("lastCloseTevEbitLtm") val lastCloseTevEbitLtm: Double,
    @SerializedName("longName") val longName: String,
    @SerializedName("market") val market: String,
    @SerializedName("marketCap") val marketCap: Long,
    @SerializedName("marketState") val marketState: String,
    @SerializedName("messageBoardId") val messageBoardId: String,
    @SerializedName("nameChangeDate") val nameChangeDate: String,
    @SerializedName("postMarketChange") val postMarketChange: Double,
    @SerializedName("postMarketChangePercent") val postMarketChangePercent: Double,
    @SerializedName("postMarketPrice") val postMarketPrice: Double,
    @SerializedName("postMarketTime") val postMarketTime: Int,
    @SerializedName("prevName") val prevName: String,
    @SerializedName("priceEpsCurrentYear") val priceEpsCurrentYear: Double,
    @SerializedName("priceHint") val priceHint: Int,
    @SerializedName("priceToBook") val priceToBook: Double,
    @SerializedName("quoteSourceName") val quoteSourceName: String,
    @SerializedName("quoteType") val quoteType: String,
    @SerializedName("region") val region: String,
    @SerializedName("regularMarketChange") val regularMarketChange: Double,
    @SerializedName("regularMarketChangePercent") val regularMarketChangePercent: Double,
    @SerializedName("regularMarketDayHigh") val regularMarketDayHigh: Double,
    @SerializedName("regularMarketDayLow") val regularMarketDayLow: Double,
    @SerializedName("regularMarketDayRange") val regularMarketDayRange: String,
    @SerializedName("regularMarketOpen") val regularMarketOpen: Double,
    @SerializedName("regularMarketPreviousClose") val regularMarketPreviousClose: Double,
    @SerializedName("regularMarketPrice") val regularMarketPrice: Double,
    @SerializedName("regularMarketTime") val regularMarketTime: Int,
    @SerializedName("regularMarketVolume") val regularMarketVolume: Int,
    @SerializedName("sharesOutstanding") val sharesOutstanding: Long,
    @SerializedName("shortName") val shortName: String,
    @SerializedName("sourceInterval") val sourceInterval: Int,
    @SerializedName("symbol") val symbol: String,
    @SerializedName("tradeable") val tradeable: Boolean,
    @SerializedName("trailingAnnualDividendRate") val trailingAnnualDividendRate: Double,
    @SerializedName("trailingAnnualDividendYield") val trailingAnnualDividendYield: Double,
    @SerializedName("trailingPE") val trailingPE: Double,
    @SerializedName("triggerable") val triggerable: Boolean,
    @SerializedName("twoHundredDayAverage") val twoHundredDayAverage: Double,
    @SerializedName("twoHundredDayAverageChange") val twoHundredDayAverageChange: Double,
    @SerializedName("twoHundredDayAverageChangePercent") val twoHundredDayAverageChangePercent: Double,
    @SerializedName("typeDisp") val typeDisp: String
)